// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZP3tAKq72w6YCb5rmGfpyYHpR0iFUqUk',
    appId: '1:335720368155:web:2bfca39a0923a552b290be',
    messagingSenderId: '335720368155',
    projectId: 'e-commerce-app-d54c8',
    authDomain: 'e-commerce-app-d54c8.firebaseapp.com',
    storageBucket: 'e-commerce-app-d54c8.appspot.com',
    measurementId: 'G-0M3LGB1M5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWWdrGyYpXtrwPKSCtFDK7pDy4DXLngY',
    appId: '1:335720368155:android:5535330570f2203db290be',
    messagingSenderId: '335720368155',
    projectId: 'e-commerce-app-d54c8',
    storageBucket: 'e-commerce-app-d54c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcL8UIbXiME8lVLsLX8MV1hoAli8duag0',
    appId: '1:335720368155:ios:56694ab099ac1c3fb290be',
    messagingSenderId: '335720368155',
    projectId: 'e-commerce-app-d54c8',
    storageBucket: 'e-commerce-app-d54c8.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcL8UIbXiME8lVLsLX8MV1hoAli8duag0',
    appId: '1:335720368155:ios:56694ab099ac1c3fb290be',
    messagingSenderId: '335720368155',
    projectId: 'e-commerce-app-d54c8',
    storageBucket: 'e-commerce-app-d54c8.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZP3tAKq72w6YCb5rmGfpyYHpR0iFUqUk',
    appId: '1:335720368155:web:7e675042c04a4562b290be',
    messagingSenderId: '335720368155',
    projectId: 'e-commerce-app-d54c8',
    authDomain: 'e-commerce-app-d54c8.firebaseapp.com',
    storageBucket: 'e-commerce-app-d54c8.appspot.com',
    measurementId: 'G-C50B6RS44V',
  );
}
